[tool.poetry]
name = "splunk_downloader"
version = "0.0.5"
description = "Download your splunk binaries with this quick tool."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
loguru = "^0.7.0"
click = "^8.1.3"
beautifulsoup4 = "^4.10.0"
pydantic = "^1.10.2"
packaging = "^23.0"

[tool.poetry.dev-dependencies]
pylint = "^2.15.5"
pytest = "^7.2.0"
black = "^23.1.0"
mypy = "^1.0"
types-requests = "^2.28.11"
pylint-pydantic = "^0.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
splunk-downloader = "splunk_downloader:cli"

[tool.pylint.MASTER]
max-line-length=200

disable="W0511,consider-using-dict-items,duplicate-code"

# https://github.com/samuelcolvin/pydantic/issues/1961#issuecomment-759522422
extension-pkg-whitelist="pydantic"
load-plugins="pylint_pydantic"
