[tool.poetry]
name = "splunk-downloader"
version = "0.0.2"
description = "Download your splunk binaries with this quick tool."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
loguru = "^0.6.0"
click = "^8.0.3"
beautifulsoup4 = "^4.10.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
pytest = "^7.0.0"
black = "^22.1.0"
mypy = "^0.931"
types-requests = "^2.27.9"
pylint-pydantic = "^0.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
