---
name: Python Linting

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  python_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Running tests
        run: |
          python --version
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run ruff check
