---
name: pytest

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.12"
      - name: Running pytest
        run: |
          python --version
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run pytest
