name: test the things

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Running pytest
        run: |
          python -m pip install .
          python -m pytest

      - name: Running mypy
        run: |
          python -m pip install .
          python -m mypy splunk_downloader

      - name: Running pylint
        run: |
          python -m pip install .
          python -m pylint --rcfile=.pylintrc splunk_downloader

